// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAroz2HHsUlf2wTUMVMjV3Q2Pecq__DgVk',
    appId: '1:932804060540:web:64f1b440bb1140cbadf0f9',
    messagingSenderId: '932804060540',
    projectId: 'chatnotification-ea545',
    authDomain: 'chatnotification-ea545.firebaseapp.com',
    storageBucket: 'chatnotification-ea545.firebasestorage.app',
    measurementId: 'G-Z8MK9JNZ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmlobfx_bc1-NX2T2rYDLahy4ngX5Jo8',
    appId: '1:932804060540:android:d6105ff0331858bbadf0f9',
    messagingSenderId: '932804060540',
    projectId: 'chatnotification-ea545',
    storageBucket: 'chatnotification-ea545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOMWFPkHR9mK-WsGFt3dVNo7Mi-4N4VI',
    appId: '1:932804060540:ios:48f9fbb808585774adf0f9',
    messagingSenderId: '932804060540',
    projectId: 'chatnotification-ea545',
    storageBucket: 'chatnotification-ea545.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOMWFPkHR9mK-WsGFt3dVNo7Mi-4N4VI',
    appId: '1:932804060540:ios:48f9fbb808585774adf0f9',
    messagingSenderId: '932804060540',
    projectId: 'chatnotification-ea545',
    storageBucket: 'chatnotification-ea545.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAroz2HHsUlf2wTUMVMjV3Q2Pecq__DgVk',
    appId: '1:932804060540:web:7e7b836365040fecadf0f9',
    messagingSenderId: '932804060540',
    projectId: 'chatnotification-ea545',
    authDomain: 'chatnotification-ea545.firebaseapp.com',
    storageBucket: 'chatnotification-ea545.firebasestorage.app',
    measurementId: 'G-MBEDSKQ6PN',
  );
}
